basePath: /
host: quiet-sands-48899.herokuapp.com
info:
  contact: {email: jasonwalsh@21.co, name: Jason Walsh, url: 'https://21.co/jasonwalsh/'}
  description: Dynamically translate text between thousands of language pairs
  license: {name: MIT, url: 'https://opensource.org/licenses/MIT'}
  termsOfService: https://opensource.org/licenses/MIT
  title: 21-translator
  version: 1.0.0
  x-21-category: utilities
  x-21-keywords: [flask, google, translate]
  x-21-quick-buy: 21 buy "https://quiet-sands-48899.herokuapp.com/?q=hello world&target=es"
  x-21-total-price: {max: 100, min: 100}
  x-21-usage: ''
paths:
  /:
    get:
      parameters:
      - {description: 'The input text to translate. Repeat this parameter to perform
          translation operations on multiple text inputs.

          ', in: query, name: q, required: true, type: string}
      - {description: 'The language to use for translation of the input text, set
          to one of the language codes listed in [Language Support](https://cloud.google.com/translate/docs/languages).

          ', in: query, name: target, required: true, type: string}
      - {description: 'The format of the source text, in either HTML (default) or
          plain-text. A value of html indicates HTML and a value of text indicates
          plain-text.

          ', in: query, name: format, type: string}
      - {description: 'The language of the source text, set to one of the language
          codes listed in [Language Support](https://cloud.google.com/translate/docs/languages).
          If the source language is not specified, the API will attempt to detect
          the source language automatically and return it within the response.

          ', in: query, name: source, type: string}
      - {description: 'The translation model. Can be either base to use the Phrase-Based
          Machine Translation (PBMT) model, or nmt to use the Neural Machine Translation
          (NMT) model. If omitted, then nmt is used.

          If the model is nmt, and the requested language translation pair is not
          supported for the NMT model, then the request is translated using the base
          model.

          ', in: query, name: model, type: string}
      produces: [text/plain]
      responses:
        200:
          description: A translated message
          schema: {type: text}
      summary: Purchase a translation
schemes: [https]
swagger: '2.0'
